# Generated by Django 4.1.2 on 2022-11-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbreakdown',
            name='Total_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
