# Generated by Django 4.1.2 on 2022-11-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homebook', '0002_cashbreakdown_total_amt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbreakdown',
            name='Total_amt',
        ),
    ]
